### PR TITLE
BAH-2306 | Show different range for lab-test

### PR DESCRIPTION
**Pull request by swe-vmd**

### CODE REVIEW

**Comment by gsluthra** [comment]
For context on this bug/request see: https://github.com/Bahmni/openmrs-module-bahmniapps/issues/441

**Comment by gsluthra** [comment]
@TriumfM Thanks for raising the PR. Can you please sign the CLA. Please ensure your email address of git commits matches your github email address which you will use to sign the CLA digitally. This is a one time activity. thanks!

**Comment by swe-vmd** [comment]
@CLAassistant @gsluthra  the CLA is accepted!

**Comment by gsluthra** [comment]
More details here: https://bahmni.atlassian.net/browse/BAH-2306

**Review by binduak — APPROVED** [review]

**Comment by binduak** [comment]
@swe-vmd CLA is still pending. As @gsluthra pointed out "your email address of git commits matches your github email address which you will use to sign the CLA digitally". Please check once

**Comment by swe-vmd** [comment]
> @swe-vmd CLA is still pending. As @gsluthra pointed out "your email address of git commits matches your github email address which you will use to sign the CLA digitally".
> 
> PR Build is failing with lint issue. https://github.com/Bahmni/openmrs-module-bahmniapps/actions/runs/3060698964/jobs/4995642567

@binduak I think now it should be okay.

**Comment by swe-vmd** [comment]
@binduak & @gsluthra this is the last push, I think now is ok but the pipeline is not running.
 https://github.com/Bahmni/openmrs-module-bahmniapps/actions/runs/3097513516

**Comment by binduak** [comment]
@swe-vmd i ran the PR checks again. CLA is still pending for the PR
Github is identifying both **@swe-vmd** and **@TriumfM** as different users/mail id's. Please check and resolve to get the CLA signed.
or you can copy the PR changes on to a different branch and commit with **@swe-vmd** user, and a raise a new PR. This should fix the issue.

**Pull request closed without merging**
