### PR TITLE
Adding travis yml

### PR DESCRIPTION
**Pull request by mdjnewman**
Travis .yml build with no notifications

### CODE REVIEW

**Comment by mdjnewman** [comment]
Hi, is this PR still under consideration?

**Comment by gsluthra** [comment]
Hello @mdjnewman. Yes this is under consideration. Thank you. I think its important that we setup travis ci again for our repos, since it helps in verifying pull requests quickly. 

There is already a build script for UI, can you see if you can hook that into your travis submission, so that unit tests also run?

**Comment by gsluthra** [comment]
Oh. I just saw. Bharat merged it. Great. Do we need to consider running unit test @bharatak?

**Comment by mdjnewman** [comment]
Hi all! This has been merged but I think it must be disabled in Travis as it's still not running.

@gsluthra - the PR that I raised will run the tests once the build is enabled in Travis :)

**Comment by mdjnewman** [comment]
Thanks for sorting this out @sravanthi17 :)

**Comment by gsluthra** [comment]
Can someone send a dummy commit to trigger a TravisCI build? I see its not
yet picked up anything.

Regards
Gurpreet

Community Lead, Bahmni
About me: http://life-lessons.in

**Pull request merged**
