### PR TITLE
Upload an existing photograph as patient profile pic

### PR DESCRIPTION
**Pull request by brookingcharlie**
Support upload of image files on a patient's registration profile. I've added a new button next to the existing webcam button that launches an upload dialog. Feedback and testing welcome.

Trello card from Open Community Work board: https://trello.com/c/VyWTPCQI

### CODE REVIEW

**Comment by brookingcharlie** [comment]
Is it normal for Travis CI builds to fail on the karma:unit step (it gets disconnected from Firefox)

**Comment by deepaucksharma** [comment]
Thanks for the PR. Here is the mingle card to track this request - https://bahmni.mingle.thoughtworks.com/projects/bahmni_emr/cards/3615

**Comment by brookingcharlie** [comment]
Would appreciate feedback on this PR from the Bahmni team!

**Comment by sumanmaity112** [comment]
Hi Charlie,
   We will merge this PR within a couple of days.

**Comment by sumanmaity112** [comment]
Hi Charlie,
We have merged your pull request and it will be available with the next release.

**Pull request merged**
