### PR TITLE
BAHMNI-30: Extending the config for a login page bottom banner.

### PR DESCRIPTION
**Pull request by mks-d**

### CODE REVIEW

**Comment by mks-d** [comment]
Hi @sumanmaity112 , what about this one, can you merge it? Any issues with it?

**Comment by sumanmaity112** [comment]
Hi Dimitri,
We will discuss this feature internally and will let you know.

**Comment by angshu** [comment]
Probably better to put a conditional check? like 

 <div class=“bottom-banner-wrapper” **ng-show=bottomBanner”**>
     
 </div>

This will ensure for those who haven't done this config.

**Comment by sumanmaity112** [comment]
Hi Dimitri,
  We have merged your pull request and it will be available with the next release.

**Comment by mks-d** [comment]
Many thanks @sumanmaity112 !

**Pull request merged**
