### PR TITLE
BAH-404 - Getting providers who are available for a…

### PR DESCRIPTION
**Pull request by sai789**
…ppointments and not changing previous providers who has appointments in past

Maharjun , Saikumar | #778 | Remove console log and fix tests

Maharjun | #778 | Include providers only when they are available for appointments in filters

Maharjun, Saikumar | #778 | should not include retired providers in providers list

https://bahmni.atlassian.net/browse/BAH-404

### CODE REVIEW

**Comment by maharjunm** [comment]
I have changed pr header message, as requested and now codacy test also passing.

**Comment by mks-d** [comment]
@maharjunm and @sai789 , there are conflicts in **appointmentConfigInitialization.js**, could you look into it?

**Comment by ShruthiPitta** [comment]
@maharjunm @mks-d  we are including this feature in 0.90. Release 0.90 will show all active providers.

**Comment by sruti-sridhar** [comment]
This fix is not a part of 0.90.  Will be part of .91.

**Comment by mks-d** [comment]
@sai789 @maharjunm , can we close this PR then?

**Comment by mks-d** [comment]
@sruti-sridhar @ShruthiPitta in your opinion can we close this PR?

**Comment by maharjunm** [comment]
@mks-d If this changes come in 0.91 release. then you can close this PR.

**Pull request closed without merging**
