### PR TITLE
registration search: strip registration prefix from registration number if present

### PR DESCRIPTION
**Pull request by mogoodrich**
See:

https://talk.openmrs.org/t/searching-for-full-patient-identifier-incl-prefix-during-registration/3809

### CODE REVIEW

**Comment by sravanthi17** [comment]
@mogoodrich 
Added comment at https://talk.openmrs.org/t/searching-for-full-patient-identifier-incl-prefix-during-registration/3809/7

**Comment by mogoodrich** [comment]
@sravanthi17 thanks!  I think that makes sense.  I am travelling out of country right now but hopefully will have time to address or follow up with questions soon, but may be a little slower than normal.

**Comment by mogoodrich** [comment]
@sravanthi17  I have updated the pull request with a further commit to strip *any* identifier prefix.  Thanks!

**Comment by sravanthi17** [comment]
@mogoodrich : 
Scenario 1: Drop down value is "GAN" and Searching with "GAN200070" works fine.
Scenario 2: Drop down value is changed to "SEM" and searching with "GAN200070" doesn't work. 
Because, the identifier prefix passed to server is from drop drown. So it will always give incorrect data.
Please let me know if you need more info on this

**Comment by mogoodrich** [comment]
Oops!  Make sense, I will fix.

**Comment by mogoodrich** [comment]
I've added a new commit that should fix scenario 2 above.  Thanks!

**Comment by sravanthi17** [comment]
@mogoodrich : Can you squash the commits ?

**Comment by mogoodrich** [comment]
@sravanthi17 I have squashed it, thanks!

**Comment by mogoodrich** [comment]
Just a little *ping* on this pull request--is it ready to be merged in?

**Comment by HemanthGowda** [comment]
Its merged in 0.83 release of Bahmni

**Comment by mogoodrich** [comment]
Thanks!

**Comment by gsluthra** [comment]
Was this feature documented on WIKI while being merged? If so, where?

**Comment by mogoodrich** [comment]
I didn't, for what it's worth... let me know if you'd like me to do anything.

**Comment by mogoodrich** [comment]
@sravanthi17 it looks like this was merged into 0.83, but *not* include 0.84, 0.85 and master--can this be forward-ported to those branches?

**Comment by sravanthi17** [comment]
Hello @mogoodrich : The functionality (searching by full patient Id still exists). But, due to some minor changes in the product the code is refactored.
https://github.com/Bahmni/openmrs-module-bahmniapps/commit/855b18df9fe96d25cbf7ada3ea8c206de1378907

**Comment by mogoodrich** [comment]
Sounds good, thanks!

**Pull request closed without merging**
