### PR TITLE
Liquibase updates needed to support error-free installation on the la…

### PR DESCRIPTION
**Pull request by mseaton**
…test 1.11 platform requirement

### CODE REVIEW

**Comment by sravanthi17** [comment]
@mseaton : Can you please give me context on what these commits are for ?

**Comment by sravanthi17** [comment]
@mseaton : Can I close this PR, looks like there are no file changes ? Please revert back if you have concerns.

**Comment by mseaton** [comment]
@sravanthi17 - I assume it can probably be closed but there are in fact file changes.  Perhaps they don't show up now because the files in question have been subsequently deleted?  Either way, we can close and re-open in the future if needed.

**Comment by sravanthi17** [comment]
Thanks for confirming @mseaton. Closing this for now.

**Pull request closed without merging**
