### PR TITLE
BAH:415 - Added condition to check Mandatory Boolean concept while saving visit page

### PR DESCRIPTION
**Pull request by Pasayadaan**
Condition for Boolean Concept on visit page

### CODE REVIEW

**Comment by Pasayadaan** [comment]
The Jira ticket [BAH415](https://bahmni.atlassian.net/browse/BAH-415?jql=). Corrected to take care of auto checks.

**Comment by Pasayadaan** [comment]
Assigned the bug to myself in JIRA and modified the title of this PR

**Comment by mks-d** [comment]
@Pasayadaan sorry I mistakenly merged this too early, I reverted the merge. Could you resubmit this as **one** commit (given the small change that it is). The issue code is BAH-415 (not BAH:415).

**Comment by Pasayadaan** [comment]
I submitted it as one commit.

 





---- On Wed, 10 Jan 2018 19:18:07 +0530 Dimitri Renault &lt;notifications@github.com&gt; wrote ----




@Pasayadaan sorry I mistakenly merged this too early, I reverted the merge. Could you resubmit this as one commit (given the small change that it is). The issue code is BAH-415 (not BAH:415).

**Pull request merged**
